#!/bin/bash
# tests/test_helper/mocks.bash — Mock utilities for Tier 2 integration tests
#
# Provides helpers to create mock executables (curl, opencode, npx, python3,
# crontab, bc) that are injected via PATH prepend. Each mock logs its
# invocation args to a file so tests can assert on what was called.
#
# Usage:
#   source tests/test_helper/mocks.bash   (after setup.bash)
#   setup_mocks                           (in bats setup())
#   teardown_mocks                        (in bats teardown())
#
# Requires: TEST_ADJ_DIR from setup.bash

# Directory where mock scripts are placed — prepended to PATH
MOCK_BIN=""
MOCK_LOG=""
_ORIGINAL_PATH=""

# --- Setup / Teardown ---

setup_mocks() {
  MOCK_BIN="${TEST_ADJ_DIR}/mock_bin"
  MOCK_LOG="${TEST_ADJ_DIR}/mock_log"
  mkdir -p "${MOCK_BIN}" "${MOCK_LOG}"
  _ORIGINAL_PATH="${PATH}"
  export PATH="${MOCK_BIN}:${PATH}"

  # Force opencode.sh to use the mock binary, not the real one.
  # opencode.sh resolves _OPENCODE_BIN once at source time via `command -v opencode`.
  # By the time setup_mocks runs, opencode.sh may already be sourced with the real
  # binary path cached. Overriding _OPENCODE_BIN here ensures opencode_run() always
  # calls the mock, preventing real OpenCode sessions from being spawned during tests.
  export _OPENCODE_BIN="${MOCK_BIN}/opencode"

  # Provide a mock `timeout` so that _adj_timeout() in opencode.sh uses it
  # instead of the shell-native fallback.  The shell fallback spawns a
  # `sleep N` watchdog that becomes an orphan after SIGKILL and can hold open
  # $() pipe FDs or cause bats to wait N seconds for it to exit.
  create_mock_timeout

  # Create additional directories Tier 2 scripts expect
  mkdir -p "${TEST_ADJ_DIR}/state/news_raw"
  mkdir -p "${TEST_ADJ_DIR}/state/news_analyzed"
  mkdir -p "${TEST_ADJ_DIR}/journal/news"
  mkdir -p "${TEST_ADJ_DIR}/photos"
  mkdir -p "${TEST_ADJ_DIR}/screenshots"
  mkdir -p "${TEST_ADJ_DIR}/prompts"
}

teardown_mocks() {
  export PATH="${_ORIGINAL_PATH}"
  unset _OPENCODE_BIN
  # Kill any leftover typing indicator background processes
  for pidfile in /tmp/adjutant_typing_*.pid; do
    [ -f "${pidfile}" ] || continue
    local pid
    pid="$(cat "${pidfile}" 2>/dev/null)"
    rm -f "${pidfile}"
    [ -n "${pid}" ] && kill "${pid}" 2>/dev/null || true
    [ -n "${pid}" ] && pkill -P "${pid}" 2>/dev/null || true
  done
  rm -f /tmp/adjutant_current_chat_job.json
}

# --- Mock Creators ---
#
# Each create_mock_* function writes a shell script to MOCK_BIN/ that:
#   1. Logs all invocation args to MOCK_LOG/<tool>.log (one call per line)
#   2. Writes the raw args to MOCK_LOG/<tool>.args (overwritten per call)
#   3. Outputs canned response text and exits with a canned exit code
#
# Arguments to create_mock_*:
#   $1 = response body (stdout)
#   $2 = exit code (default 0)

# Generic mock creator — used by all create_mock_* wrappers
_create_mock() {
  local name="$1"
  local response="${2:-}"
  local exit_code="${3:-0}"
  local mock_script="${MOCK_BIN}/${name}"

  cat > "${mock_script}" <<MOCK_SCRIPT
#!/bin/bash
# Mock ${name} — auto-generated by mocks.bash
echo "\$@" >> "${MOCK_LOG}/${name}.log"
printf '%s\\n' "\$@" > "${MOCK_LOG}/${name}.args"
cat <<'RESPONSE'
${response}
RESPONSE
exit ${exit_code}
MOCK_SCRIPT
  chmod +x "${mock_script}"
}

# Create a mock with a custom script body (for complex behavior)
_create_mock_custom() {
  local name="$1"
  local body="$2"
  local mock_script="${MOCK_BIN}/${name}"

  cat > "${mock_script}" <<MOCK_SCRIPT
#!/bin/bash
# Mock ${name} — custom auto-generated by mocks.bash
echo "\$@" >> "${MOCK_LOG}/${name}.log"
printf '%s\\n' "\$@" > "${MOCK_LOG}/${name}.args"
${body}
MOCK_SCRIPT
  chmod +x "${mock_script}"
}

# --- Specific Mock Creators ---

# curl — returns canned JSON response
# Args: $1 = response body, $2 = exit code (default 0)
create_mock_curl() {
  local response="${1:-\{\"ok\":true,\"result\":\{\}\}}"
  _create_mock "curl" "${response}" "${2:-0}"
}

# curl with Telegram-style success response
create_mock_curl_telegram_ok() {
  create_mock_curl '{"ok":true,"result":{"message_id":42}}'
}

# curl with Telegram-style error response
create_mock_curl_telegram_error() {
  local description="${1:-Bad Request: message text is empty}"
  create_mock_curl "{\"ok\":false,\"error_code\":400,\"description\":\"${description}\"}"
}

# opencode — returns canned NDJSON output (one line per event)
# Args: $1 = NDJSON content (multiline), $2 = exit code (default 0)
create_mock_opencode() {
  local ndjson="${1:-}"
  local exit_code="${2:-0}"

  _create_mock_custom "opencode" "
cat <<'NDJSON_RESPONSE'
${ndjson}
NDJSON_RESPONSE
exit ${exit_code}
"
}

# opencode that returns a simple text reply
create_mock_opencode_reply() {
  local reply_text="${1:-Hello from mock opencode}"
  local session_id="${2:-mock-session-001}"
  create_mock_opencode "{\"type\":\"session.create\",\"sessionID\":\"${session_id}\"}
{\"type\":\"text\",\"part\":{\"text\":\"${reply_text}\"}}
{\"type\":\"text.done\"}"
}

# opencode that returns a model-not-found error
create_mock_opencode_model_error() {
  create_mock_opencode '{"type":"error","error":{"name":"ModelNotFound","data":{"message":"Model not found: bad-model"}}}'
}

# opencode with a models subcommand — returns a list of model names
create_mock_opencode_models() {
  local models="${1:-anthropic/claude-haiku-4-5
anthropic/claude-sonnet-4-20250514}"
  _create_mock_custom "opencode" "
if [[ \"\$1\" == \"models\" ]]; then
  cat <<'MODELS'
${models}
MODELS
  exit 0
fi
# Default: NDJSON for run commands
echo '\$@' >> '${MOCK_LOG}/opencode.log'
cat <<'NDJSON_RESPONSE'
{\"type\":\"text\",\"part\":{\"text\":\"mock reply\"}}
NDJSON_RESPONSE
exit 0
"
}

# node — for playwright_screenshot.mjs and other Node scripts
# Args: $1 = response text, $2 = exit code
create_mock_node() {
  local response="${1:-}"
  local exit_code="${2:-0}"
  # The screenshot script calls: node <script_path> <url> <outfile>
  # We need to create the outfile so screenshot.sh doesn't fail on the file-exists check.
  _create_mock_custom "node" "
# Find the outfile argument: node <script> <url> <outfile>
args=(\"\$@\")
if [ \${#args[@]} -ge 3 ]; then
  outfile=\"\${args[\${#args[@]}-1]}\"
  # Create a fake PNG (1x1 pixel header)
  printf '\\x89PNG\\r\\n\\x1a\\n' > \"\${outfile}\" 2>/dev/null || true
fi
cat <<'NODE_RESPONSE'
${response}
NODE_RESPONSE
exit ${exit_code}
"
}

# npx — for Playwright screenshot mocking
# Args: $1 = response text, $2 = exit code
create_mock_npx() {
  local response="${1:-}"
  local exit_code="${2:-0}"
  # npx playwright screenshot needs to create the output file
  _create_mock_custom "npx" "
# Find the output file argument (last arg to playwright screenshot)
args=(\"\$@\")
outfile=\"\${args[\${#args[@]}-1]}\"
if [[ \"\$1\" == \"playwright\" && \"\$2\" == \"screenshot\" ]]; then
  # Create a fake PNG (1x1 pixel)
  printf '\\x89PNG\\r\\n\\x1a\\n' > \"\${outfile}\" 2>/dev/null || true
fi
cat <<'NPX_RESPONSE'
${response}
NPX_RESPONSE
exit ${exit_code}
"
}

# python3 — for URL domain parsing in screenshot.sh
# Args: $1 = response text (domain), $2 = exit code
create_mock_python3() {
  _create_mock_custom "python3" "
# screenshot.sh calls python3 -c 'from urllib.parse ... print(d[:40])'
# Just echo a canned domain
echo '${1:-example.com}'
exit ${2:-0}
"
}

# crontab — returns canned crontab output
# Args: $1 = crontab lines, $2 = exit code
create_mock_crontab() {
  _create_mock "crontab" "${1:-}" "${2:-0}"
}

# bc — real bc is needed for float math; mock only if unavailable
# For most tests we just use the real bc. This mock is for edge cases.
create_mock_bc() {
  _create_mock "bc" "${1:-0}" "${2:-0}"
}

# timeout — wraps the real command execution (just exec the rest of args)
create_mock_timeout() {
  _create_mock_custom "timeout" '
# Skip the timeout duration arg and exec the rest
shift  # remove timeout duration
exec "$@"
'
}

# jq — we always use the real jq (it's a prerequisite), but provide this
# for tests that need to verify behavior when jq is missing
create_mock_jq_missing() {
  _create_mock_custom "jq" "
echo 'jq: command not found' >&2
exit 127
"
}

# --- Assertion Helpers ---

# Assert that a mock was called at least once
# Args: $1 = mock name
assert_mock_called() {
  local name="$1"
  local log="${MOCK_LOG}/${name}.log"
  [ -f "${log}" ] || fail "Mock '${name}' was never called (no log file)"
  [ -s "${log}" ] || fail "Mock '${name}' was never called (empty log file)"
}

# Assert that a mock was never called
assert_mock_not_called() {
  local name="$1"
  local log="${MOCK_LOG}/${name}.log"
  if [ -f "${log}" ] && [ -s "${log}" ]; then
    fail "Mock '${name}' was unexpectedly called: $(cat "${log}")"
  fi
}

# Get the number of times a mock was called
mock_call_count() {
  local name="$1"
  local log="${MOCK_LOG}/${name}.log"
  [ -f "${log}" ] || { echo "0"; return; }
  wc -l < "${log}" | tr -d ' '
}

# Assert a mock was called exactly N times
assert_mock_call_count() {
  local name="$1"
  local expected="$2"
  local actual
  actual="$(mock_call_count "${name}")"
  [ "${actual}" -eq "${expected}" ] || fail "Mock '${name}' called ${actual} times, expected ${expected}"
}

# Get the last args a mock was called with
mock_last_args() {
  local name="$1"
  local log="${MOCK_LOG}/${name}.log"
  [ -f "${log}" ] || { echo ""; return; }
  tail -1 "${log}"
}

# Assert that a mock's last call contained a specific string
assert_mock_args_contain() {
  local name="$1"
  local expected="$2"
  local actual
  actual="$(mock_last_args "${name}")"
  [[ "${actual}" == *"${expected}"* ]] || fail "Mock '${name}' args did not contain '${expected}'. Got: ${actual}"
}

# Get the Nth call args (1-indexed)
mock_call_args() {
  local name="$1"
  local n="$2"
  local log="${MOCK_LOG}/${name}.log"
  [ -f "${log}" ] || { echo ""; return; }
  sed -n "${n}p" "${log}"
}

# --- State Seeding Helpers ---

# Seed a telegram session file
seed_telegram_session() {
  local session_id="${1:-test-session-123}"
  local epoch="${2:-$(date +%s)}"
  local human="${3:-$(date '+%H:%M %d.%m.%Y')}"
  cat > "${TEST_ADJ_DIR}/state/telegram_session.json" <<JSON
{"session_id":"${session_id}","last_message_epoch":${epoch},"last_message_at":"${human}"}
JSON
}

# Seed a model file
seed_model_file() {
  local model="${1:-anthropic/claude-haiku-4-5}"
  printf '%s' "${model}" > "${TEST_ADJ_DIR}/state/telegram_model.txt"
}

# Seed a heartbeat file
seed_heartbeat() {
  local timestamp="${1:-$(date -u +"%Y-%m-%dT%H:%M:%SZ")}"
  local summary="${2:-All systems nominal.}"
  cat > "${TEST_ADJ_DIR}/state/last_heartbeat.json" <<JSON
{"timestamp":"${timestamp}","findings":"${summary}"}
JSON
}

# Seed a usage log (JSONL)
seed_usage_log() {
  local content="$1"
  printf '%s\n' "${content}" > "${TEST_ADJ_DIR}/state/usage_log.jsonl"
}

# Seed a news config
seed_news_config() {
  local config="${1:-}"
  if [ -z "${config}" ]; then
    config='{
  "keywords": ["AI agent", "autonomous agent"],
  "sources": {
    "hackernews": {"enabled": true, "max_items": 5, "lookback_hours": 24},
    "reddit": {"enabled": false},
    "blogs": {"enabled": false}
  },
  "analysis": {
    "prefilter_limit": 5,
    "top_n": 3,
    "model": "anthropic/claude-haiku-4-5"
  },
  "delivery": {
    "telegram": true,
    "journal": true
  },
  "deduplication": {
    "window_days": 30
  },
  "cleanup": {
    "raw_retention_days": 7,
    "analyzed_retention_days": 7
  }
}'
  fi
  printf '%s' "${config}" > "${TEST_ADJ_DIR}/news_config.json"
}

# Seed raw news file for today
seed_raw_news() {
  local content="${1:-[]}"
  local today
  today="$(date +%Y-%m-%d)"
  printf '%s' "${content}" > "${TEST_ADJ_DIR}/state/news_raw/${today}.json"
}

# Seed analyzed news file for today
seed_analyzed_news() {
  local content="${1:-[]}"
  local today
  today="$(date +%Y-%m-%d)"
  printf '%s' "${content}" > "${TEST_ADJ_DIR}/state/news_analyzed/${today}.json"
}

# Seed the dedup file
seed_news_dedup() {
  local content="${1:-\{\"urls\":[]\}}"
  printf '%s' "${content}" > "${TEST_ADJ_DIR}/state/news_seen_urls.json"
}

# Seed a prompt file
seed_prompt() {
  local name="$1"
  local content="${2:-# Test prompt}"
  printf '%s' "${content}" > "${TEST_ADJ_DIR}/prompts/${name}"
}

# Seed a pending reflect flag
seed_pending_reflect() {
  touch "${TEST_ADJ_DIR}/state/pending_reflect"
}
